# Generated by Django 5.1.2 on 2024-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish_reason',
            field=models.CharField(choices=[('checkmate', 'Мат'), ('stalemate', 'Пат'), ('resignation', 'Сдача'), ('insufficient_material', 'Недостаточно материала'), ('threefold_repetition', 'Троекратное повторение'), ('fifty_move_rule', 'Правило 50 ходов')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_colour',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], max_length=10, null=True),
        ),
    ]
